function() {
    try {
        throw new Error('Caught Error');
    } catch (ex) {}
}